#!/bin/bash

# process options
while getopts p:o:n:u:i: option
do
	case "${option}"
    in
		p) PORT=${OPTARG};;
		o) ORIGIN=${OPTARG};;
		n) NAME=${OPTARG};;
		u) USERNAME=${OPTARG};;
		i) KEYFILE=${OPTARG};;
	esac
done

# build array of replca servers
REPLICAS=("ec2-54-210-1-206.compute-1.amazonaws.com"
"ec2-54-67-25-76.us-west-1.compute.amazonaws.com" 
"ec2-35-161-203-105.us-west-2.compute.amazonaws.com" 
"ec2-52-213-13-179.eu-west-1.compute.amazonaws.com" 
"ec2-52-196-161-198.ap-northeast-1.compute.amazonaws.com" 
"ec2-54-255-148-115.ap-southeast-1.compute.amazonaws.com" 
"ec2-13-54-30-86.ap-southeast-2.compute.amazonaws.com" 
"ec2-52-67-177-90.sa-east-1.compute.amazonaws.com" 
"ec2-35-156-54-135.eu-central-1.compute.amazonaws.com")


#=========== RUN HTTP SERVER ON REPLICAS

# for each replica serve
for i in "${REPLICAS[@]}"
do
   : 
   # start up the HTTP server
    ssh -i $KEYFILE -n -f $USERNAME@$i bash -c "echo pwd; nohup ./httpserver -p $PORT -o $ORIGIN > httpserver.out 2>&1 &"
done
#=========== RUN DNS ON cs5700cdnproject.ccs.neu.edu

#start up the DNS server
ssh -i $KEYFILE -n -f $USERNAME@cs5700cdnproject.ccs.neu.edu bash -c "echo pwd; nohup ./dnsserver -p $PORT -n $NAME > dnsserver.out 2>&1 &"
